### ISSUE TITLE
[Task] Add validation support for file uploads

### ISSUE THREAD

**Issue by tjtanjin** [react-chatbotify-plugins/input-validator#1]
**Task Description**
The plugin currently provides support for validating user input only in the form of text. However, users may submit file uploads as well and there may be use cases for validating them. It would be nice if the plugin also supports validation for file uploads.

**Deliverable(s)**
Propose and implement a solution for supporting file upload validation (e.g. by adding a new attribute). Some ideas come to mind but I'll leave this intentionally vague to see what other interesting approaches there might be 😝

**Comment by tasbi03** [comment]
hey , assign me please!!

**Comment by tjtanjin** [comment]
> hey , assign me please!!
> 
> 

Go for it! 😊
